import { computed } from 'vue'
import { defineStore } from 'pinia'

export const useFlowerStore = defineStore('flower', () => {
  const flowers = computed(() => {
    // TODO pull flowers from local storage with pricing
    return [
      "Rose",
      "Tulip",
      "Lily",
      "Carnation",
      "Chrysanthemum",
      "Peony",
      "Hydrangea",
      "Orchid",
      "Sunflower",
      "Baby's Breath",
      "Daisy",
      "Ranunculus",
      "Anemone",
      "Gardenia",
      "Freesia",
      "Dahlia",
      "Calla Lily",
      "Alstroemeria",
      "Gerbera Daisy",
      "Lavender",
      "Sweet Pea",
      "Snapdragon",
      "Stock",
      "Lisianthus",
      "Magnolia",
      "Camellia",
      "Zinnia",
      "Marigold",
      "Cosmos",
      "Poppy",
      "Heather",
      "Delphinium",
      "Iris",
      "Gladiolus",
      "Protea",
      "King Protea",
      "Scabiosa",
      "Veronica",
      "Waxflower",
      "Statice",
      "Aster",
      "Amaryllis",
      "Hellebore",
      "Lilac",
      "Jasmine",
      "Stephanotis",
      "Tuberose",
      "Yarrow",
      "Queen Anne's Lace",
      "Clematis",
      "Wisteria",
      "Bluebell",
      "Cornflower",
      "Nigella",
      "Foxglove",
      "Hibiscus",
      "Bougainvillea",
      "Bird of Paradise",
      "Anthurium",
      "Heliconia",
      "Bells of Ireland",
      "Allium",
      "Craspedia",
      "Billy Balls",
      "Chamelaucium",
      "Pincushion Protea",
      "Larkspur",
      "Amaranthus",
      "Celosia",
      "Globe Thistle",
      "Eryngium",
      "Dusty Miller",
      "Silver Brunia",
      "Pittosporum",
      "Ruscus",
      "Eucalyptus",
      "Myrtle",
      "Olive Branch",
      "Fern",
      "Hosta Leaf",
      "Peach Blossom",
      "Apple Blossom",
      "Cherry Blossom",
      "Forsythia",
      "Mock Orange",
      "Viburnum",
      "Snowberry",
      "Hypericum Berry",
      "Rosehip",
      "Camomile",
      "Matthiola",
      "Phlox",
      "Begonia",
      "Primrose",
      "Geranium",
      "Verbena",
      "Coreopsis",
      "Gaillardia",
      "Lupine",
      "Columbine",
      "Buttercup",
      "Crocus",
      "Hyacinth",
      "Blue Thistle"
    ]

  })


  return { flowers }
})
